version: '2'
services:
    betadata-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/betaData/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=betaData
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
